# use latest 2.1 version of CircleCI pipeline
version: 2.1

# use a package of configuration called an orb
orbs:
  react: 'thefrontside/react@dev:alpha'

workflows:
  push:
    jobs:
      - react/install
      - react/eslint:
          requires:
            - react/install
      - react/test:
          requires:
            - react/install
      - react/coverage:
          requires:
            - react/install
